name = "spxnso/iro"
version = "1.0.0"
repository = "https://github.com/spxnso/iro"
description = "Lightweight library for rich, terminal-style colored text output"
authors = ["spxnso"]
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
]

[target]
environment = "luau"
lib="src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
